### ISSUE TITLE
[Feature Request] Needs more miata.

### ISSUE THREAD

**Issue by stobias123** [jfmatth/jnl.3756home.org#1]
Hi, I'm noticing a striking lack of miata content on this website. This feature request is to add more miata.

![image](https://github.com/jfmatth/jnl.3756home.org/assets/590677/9bacff8b-1ce6-450d-9cf1-404b9e73268a)

**Comment by jfmatth** [comment]
Well, considering I just now figured out what theme I was going to use, it might take a bit.
